# Generated by Django 5.2.8 on 2025-12-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, unique=True)),
                ("slug", models.SlugField(max_length=40, unique=True)),
                ("release_date", models.DateField()),
                ("price", models.PositiveIntegerField()),
                ("image", models.URLField(max_length=160, unique=True)),
                ("lte_exists", models.BooleanField()),
            ],
        ),
    ]
